# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('pswd', models.CharField(max_length=250)),
                ('nickname', models.CharField(max_length=20)),
            ],
        ),
    ]
