# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('event', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
