# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_auto_20180213_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
