# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_auto_20180213_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='starting',
        ),
    ]
