# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0005_auto_20180220_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starting',
            name='event',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 15, 29, 4, 15000)),
        ),
    ]
