# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0012_auto_20180220_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='starting',
            name='events',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
