# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0015_auto_20180305_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_testcases',
            name='label',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
