# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0016_other_testcases_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_testcases',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
