# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0017_auto_20180305_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='testbed_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(max_length=20)),
                ('Tims_id', models.CharField(max_length=50)),
                ('adapter_name', models.CharField(max_length=9999)),
                ('osname', models.CharField(max_length=100)),
                ('boot_method', models.CharField(max_length=100)),
                ('boot_adapter', models.CharField(max_length=100)),
                ('event', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
